### ISSUE TITLE
Model for VAE

### ISSUE THREAD

**Issue by ninasinger** [MaciejZamorski/3d-AAE#3]
Are you able to make the model for the variational autoencoder available?
I noticed that it was there in your hyperparameters.json as an example but not in the model's folder.
Thanks

**Comment by levtelyatnikov** [comment]
> Are you able to make the model for the variational autoencoder available?
> I noticed that it was there in your hyperparameters.json as an example but not in the model's folder.
> Thanks

Hello, have you found variational autoencoder?
